# 開発環境専用 Compose ファイル
# 実行: docker compose -f compose.yml -f compose.dev.yml up

services:
  # Keycloak 26 LTS - OAuth2/OIDC認証基盤（開発環境のみ）
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: circleportal-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/circleportal
      KC_DB_USERNAME: circleportal
      KC_DB_PASSWORD: circleportal
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_PROTOCOL: http
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "exec 3<>/dev/tcp/localhost/8080; echo -e 'GET /health/ready HTTP/1.1\\nhost: localhost\\nConnection: close\\n' >&3; grep '200 OK' <&3 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
